# Generated by Django 4.0 on 2022-06-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_neighborhood_description_neighborhood_health_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='neighborhood_name',
            new_name='name',
        ),
    ]
